"""initial schema

Revision ID: 2a8f84db17e8
Revises: 
Create Date: 2026-03-31 10:38:36.684725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2a8f84db17e8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brokers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=500), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('customers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('employment_type', sa.Enum('employed', 'self_employed', 'contractor', 'retired', 'other', name='employmenttype'), nullable=True),
    sa.Column('annual_income', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('deposit_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('property_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('property_type', sa.Enum('detached', 'semi_detached', 'terraced', 'flat', 'bungalow', 'new_build', 'other', name='propertytype'), nullable=True),
    sa.Column('mortgage_type', sa.Enum('purchase', 'remortgage', name='mortgagetype'), nullable=True),
    sa.Column('mortgage_term_years', sa.Integer(), nullable=True),
    sa.Column('first_time_buyer', sa.Boolean(), nullable=True),
    sa.Column('property_location', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('in_progress', 'submitted', 'reviewed', 'approved', 'declined', name='customerstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('lenders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('banking_analyses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('salary_frequency', sa.Enum('weekly', 'fortnightly', 'monthly', 'irregular', name='salaryfrequency'), nullable=True),
    sa.Column('salary_regularity_score', sa.Integer(), nullable=True),
    sa.Column('average_salary', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salary_variation_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('flagged_expenses', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('estimated_monthly_rent', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_monthly_commitments', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('analysis_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('banking_connections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('truelayer_connection_id', sa.String(length=500), nullable=True),
    sa.Column('access_token', sa.String(length=2000), nullable=True),
    sa.Column('provider_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('pending', 'connected', 'expired', 'error', name='connectionstatus'), nullable=False),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consent_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('messages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eligibility_criteria',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lender_id', sa.Integer(), nullable=False),
    sa.Column('source_crit_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('criterion_name', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('grade', sa.Enum('yes', 'no', 'refer', 'condition', 'yes_by_exception', name='criteriagrade'), nullable=True),
    sa.Column('details_text', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('lending_type', sa.Enum('residential', 'buy_to_let', name='lendingtype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lender_id'], ['lenders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lender_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('product_type', sa.Enum('fixed', 'variable', 'tracker', 'discount', name='producttype'), nullable=False),
    sa.Column('rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('rate_type', sa.String(length=50), nullable=False),
    sa.Column('initial_period_months', sa.Integer(), nullable=False),
    sa.Column('svr_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('min_ltv', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('max_ltv', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('min_loan', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('max_loan', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('arrangement_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('booking_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cashback', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('min_income', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('max_income_multiple', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('first_time_buyer_eligible', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lender_id'], ['lenders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('match_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('match_reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('unmet_criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('customer_summary_text', sa.Text(), nullable=True),
    sa.Column('broker_summary_text', sa.Text(), nullable=True),
    sa.Column('broker_id', sa.Integer(), nullable=True),
    sa.Column('broker_approved', sa.Boolean(), nullable=True),
    sa.Column('broker_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['broker_id'], ['brokers.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recommendations')
    op.drop_table('products')
    op.drop_table('eligibility_criteria')
    op.drop_table('conversations')
    op.drop_table('banking_connections')
    op.drop_table('banking_analyses')
    op.drop_table('lenders')
    op.drop_table('customers')
    op.drop_table('brokers')
    # ### end Alembic commands ###
